### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by shervinbdndev** [Alirezaaraby/Rouigram#2]
![Screenshot_20220310-181802_GitHub.jpg](https://user-images.githubusercontent.com/68682979/157686998-9c6e8dfa-2a8d-418a-a7b6-10cb7175a631.jpg)

**Comment by Alirezaaraby** [comment]
Hi, thanks for your issue. But what do you mean? I didn't get it

**Comment by shervinbdndev** [comment]
> Hi, thanks for your issue. But what do you mean? I didn't get it

I mean the typography...your readme file has an incorrect word that I highlighted before in the picture.
